
package demo.spring.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.6
 * Fri Aug 19 16:31:42 IST 2016
 * Generated source version: 3.1.6
 */

@XmlRootElement(name = "sayHiResponse", namespace = "http://service.spring.demo/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sayHiResponse", namespace = "http://service.spring.demo/")

public class SayHiResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

